package com.example.common.reponse;

/**
 * 请求异常的枚举类  后期所有code 这里维护
 */
public enum ExceptionEnum {

    SUCCESS("0","SUCCESS"),
    ERROR("1","ERROR"),
    PARAM_ERROR("-1","PARAM_ERROR"),
    RESULT_FAILED("-2","RESULT_FAILED"),
    INVALID_TOKEN("-3","INVALID_TOKEN"),
    SIGNATURE_ERROR("-4","SIGNATURE_ERROR"),

    /**
     * 设备相关10000
     */

    DEVICE_EXIST("4","DEVICE_EXIST"),
    DEVICE_NOT_SUPPORTED("10000","DEVICE_NOT_SUPPORTED"),
    DEVICE_OFFLINE("10001","DEVICE_OFFLINE"),
    DEVICE_EXCEED_LIMIT("10002","DEVICE_EXCEED_LIMIT"),
    DEVICE_LOW_MEMORY("10003","DEVICE_LOW_MEMORY"),
    DEVICE_BUSY("10004","DEVICE_BUSY"),
    DEVICE_NOT_EXIST ("10005","DEVICE_NOT_EXIST"),
    DEVICE_REGISTERED("10006","DEVICE_REGISTERED"),
    DEVICE_VERSION_NOT_EXIST("10007","DEVICE_VERSION_NOT_EXIST"),
    DEVICE_INVALID("10008","DEVICE_INVALID"),
    DEVICE_INITIALIZED("10009","DEVICE_INITIALIZED"),
    DEVICE_CHANNEL_FULL("10010","DEVICE_CHANNEL_FULL"),
    DEVICE_UPGRADE_IN("10011","DEVICE_UPGRADE_IN"),
    DEVICE_INSTALL_IN("10012","DEVICE_INSTALL_IN"),
    DEVICE_RESULT_FAILED("10013","DEVICE_RESULT_FAILED"),
    DEVICE_SEARCH_FAILED("10014","DEVICE_SEARCH_FAILED"),
    REQUEST_TIMEOUT("10015","REQUEST_TIMEOUT"),
    DEVICE_NO_PERMISSION("10016","DEVICE_NO_PERMISSION"),
    RESULT_DUPLICATE("10017","RESULT_DUPLICATE"),
    JSON_ERR("10021","JSON_ERR"),
    RESULT_NOT_SUPPORTED("10031","RESULT_NOT_SUPPORTED"),
    PLATFORM_IS_NULL("10032","PLATFORM_IS_NULL"),

    TOKEN_NOT_EXIT("9990001","TOKEN_NOT_EXIT"),
    TOKEN_EXPIRATION("9990002","TOKEN_EXPIRATION"),
    /**
     * 平台相关20000
     */
    PLATFORM_NOT_EXIST("20000","PLATFORM_NOT_EXIST"),

    /**
     * 门店相关30000
     */
    SHOP_NOT_EXIST("30000","SHOP_NOT_EXIST"),

    /**
     * 异常错误
     */
    RESULT_EXCEPTION("99999","RESULT_EXCEPTION"),
    CLOUD_EXCEPTION("199999","CLOUD_EXCEPTION"),

    /**
     * 抓拍50000
     */
    RESULT_HAND_CAPTURE_SCENE("50000","RESULT_HAND_CAPTURE_SCENE"),
    RESULT_DELETED_SCENE("50001","RESULT_DELETED_SCENE"),
    RESULT_DISABLED_SCENE("50002","RESULT_DISABLED_SCENE"),
    RESULT_DEVICE_NOT_EXIST("50003","RESULT_DEVICE_NOT_EXIST"),

    /**
     * dms 60000
     */
    START_REC_DOWN_FAIL("60001","START_REC_DOWN_FAIL"),
    START_REC_DOWN_IPC_NOT_EXIST("60002","START_REC_DOWN_IPC_NOT_EXIST"),
    START_REC_DOWN_IPC_IS_PALYING("60003","START_REC_DOWN_IPC_IS_PALYING"),
    START_REC_DOWN_NOPLYER_ERR("60004","START_REC_DOWN_NOPLYER_ERR"),
    START_REC_DOWN_ERR_PER_LACK_CPU("60005","START_REC_DOWN_ERR_PER_LACK_CPU"),
    START_REC_DOWN_ERR_NVR_DOWNOPP_EXIST("60006","START_REC_DOWN_ERR_NVR_DOWNOPP_EXIST"),
    NO_VIDEO("60010","NO_VIDEO"),
    NVR_NO_DATA("60011","NVR_NO_DATA"),
    NVR_EXCEPTION("60012","NVR_EXCEPTION"),
    RESULT_DEVICE_OFFLINE("60020","RESULT_DEVICE_OFFLINE"),
    RESULT_DEVICE_LOW_MEMORY("60021","RESULT_DEVICE_LOW_MEMORY"),
    RESULT_DEVICE_BUSY("60022","RESULT_DEVICE_BUSY"),
    DMS_CODE_DEVICE_PARAMETER_ERR("60023","DMS_CODE_DEVICE_PARAMETER_ERR"),
    DMS_CODE_DEVICE_REQUEST_FAILED("60024","DMS_CODE_DEVICE_REQUEST_FAILED"),
    DMS_CODE_DEVICE_EQP_ERR("60025","DMS_CODE_DEVICE_EQP_ERR"),
    DMS_CODE_DEVICE_UNKNOWN_ERR("60026","DMS_CODE_DEVICE_UNKNOWN_ERR"),
    DMS_CODE_DEVICE_RTSP_ERR("60027","DMS_CODE_DEVICE_RTSP_ERR"),
    DMS_CODE_DEVICE_RTMP_ERR("60028","DMS_CODE_DEVICE_RTMP_ERR"),
    DMS_CODE_DEVICE_RTMP_REC_ERR("60029","DMS_CODE_DEVICE_RTMP_REC_ERR"),
    DMS_CODE_DEVICE_MEDIA_NOT_SUPPORTED("60030","DMS_CODE_DEVICE_MEDIA_NOT_SUPPORTED"),
    DMS_CODE_DEVICE_DATA_SWITCH_ERR("60031","DMS_CODE_DEVICE_DATA_SWITCH_ERR"),
    DMS_CODE_DEVICE_DMS_TIMEOUT("60032","DMS_CODE_DEVICE_DMS_TIMEOUT"),
    DMS_CODE_DEVICE_DUMP_CMD_RESP_ERR("60033","DMS_CODE_DEVICE_DUMP_CMD_RESP_ERR"),
    DMS_CODE_DEVICE_PARSE_CMD_RESP_ERR("60034","DMS_CODE_DEVICE_PARSE_CMD_RESP_ERR"),
    NOT_SUPPORT("60035","NOT_SUPPORT"),
    CAPABILITY_TYPE_DOWNLOAD_TS_REC("60036","CAPABILITY_TYPE_DOWNLOAD_TS_REC"),
    DMS_CODE_DEVICE_COMM_TIMEOUT("60037","DMS_CODE_DEVICE_COMM_TIMEOUT"),
    ;

    private String code;
    private String message;

    ExceptionEnum(String code, String message){
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}